### ISSUE TITLE
Loading Model from State Dictionary throws Unexpected Keys Error

### ISSUE THREAD

**Issue by ThomSab** [tigerchen52/GLADIS#2]
Hi I tried using the AcroBert model on my machine and ran into an error:

I ran the installation as described in the Repo.
Downloaded the model and the dictionary from the given [link](https://zenodo.org/records/7568937#.Y9JiQXaZNPY).

As I try to try to run the acrobert.py script in the `.\inference\` folder like this: 

`GLADIS\inference> py .\acrobert.py`

it loads the dictionary:

`2024-04-26 16:32:02,565 : utils.py : load_acronym_kb : INFO : loaded acronym dictionary successfully, in total there are [1542845] acronyms `
`2024-04-26 16:32:02,565 : acrobert.py : <module> : INFO : running .\acrobert.py`

but then throws:

`RuntimeError: Error(s) in loading state_dict for AcronymBERT:
        Unexpected key(s) in state_dict: "model.bert.embeddings.position_ids".`

Im running Python 3.11.4 on Windows 11.
I have installed all requirements and updated all my modules.
I have re-downloaded the repo and the model files multiple times.

Am I doing something wrong?
Do you have an idea what might cause this? 
Does it behave the same way on your machine?

Any help is appreciated!

Best,
Jasper

**Comment by tigerchen52** [comment]
Dear Jasper, 

Thanks for your interest in our work. 

I have met the same error before and it seems that it is caused by the compatibility of python packages. I would recommend checking the version of transformers. Recently I'm moving, but I can have a deep look later. Please keep discussing in this channel if the error is not fixed.

Warm regards,

Lihu

**Comment by ThomSab** [comment]
Hi Lihu

Thanks for your answer!
I haven't gotten it to work yet. I tried with the current transformers version from pip (4.40.1) and also tried to run it with a manually installed version from the github repo (4.41.0.dev0).
Can you let me know which transformers version you got it to run on?

Best 
Jasper

**Comment by tigerchen52** [comment]
Hey Jasper,

Can you have a try on this version in the [requirement.txt](https://huggingface.co/spaces/Lihuchen/AcroBERT/blob/main/requirements.txt). I can run it successfully. Let me know your feedback so that I can update the requirement file in this repo. Thanks!

Best,

Lihu

**Comment by ThomSab** [comment]
Hi,

I finally got around to install the old version and try to get it running.
Worked out fine,  thanks for the Help!

Best,
Jasper
